### ISSUE TITLE
Error: Cannot find module 'ical.js'

### ISSUE THREAD

**Issue by cypyhou** [eouia/MMM-CalendarExt2#64]
Hi,

Just getting a [Raspberry Pi Zero setup with MagicMirror](http://emmanuelcontreras.com/how-to/how-to-create-a-magic-mirror-2-with-pi-zero-w/) and ran into some dependency errors when installing MMM-CalendarExt2.

The first error was for "moment-timezone" which was fixed by:
npm install moment-timezone

The next error is with ical.js, and I'm struggling to find what needs installing:

[14:34:03.721] [ERROR]  { Error: Cannot find module 'ical.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CalendarExt2/node_helper.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) code: 'MODULE_NOT_FOUND' }

Ideas?

Cheers,
Kevin.

**Comment by cypyhou** [comment]
My bad. Need cd into the module to do the npm install... :-|
